name: build
on: [pull_request]

jobs:
  build:
    if: github.repository_owner == 'hazelcast'
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v4
      - name: Read Java Config
        uses: pietrobolcato/action-read-yaml@9f13718d61111b69f30ab4ac683e67a56d254e1d
        id: java-config
        with:
          config: ${{ github.workspace }}/.github/java-config.yml
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ steps.java-config.outputs['java-version'] }}
          architecture: 'x64'
          distribution: ${{ steps.java-config.outputs['distribution'] }}
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw clean package -V -B -P checkstyle,findbugs
