name: Deploy SNAPSHOT version
on:
  push:
    branches:
      - 'main'
      - '[0-9]+.[0-9]+.z'
    paths-ignore:
      - '**.md'

jobs:
  build:
    if: github.repository_owner == 'hazelcast'
    runs-on: ubuntu-latest
    name: Build SNAPSHOT version
    steps:
      - uses: actions/checkout@v4
      - name: Read Java Config
        uses: pietrobolcato/action-read-yaml@1.1.0
        id: java-config
        with:
          config: ${{ github.workspace }}/.github/java-config.yml
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ steps.java-config.outputs['java-version'] }}
          distribution: ${{ steps.java-config.outputs['distribution'] }}
          server-id: deploy-repository
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          architecture: 'x64'
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw -V -B install

      - name: Deploy OS with Maven
        run: ./mvnw -V -B deploy -Djdbc-release -DskipTests
        env:
          MAVEN_USERNAME: ${{ secrets.SONATYPE_OSS_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.SONATYPE_OSS_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

      - name: Deploy EE with Maven
        run: ./mvnw -f hazelcast-jdbc-enterprise -V -B deploy -Djdbc-release -DskipTests
        env:
          MAVEN_USERNAME: ${{ secrets.JFROG_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
